Mobile-First Pull Request
skabeo/Mobile-First pull request #1
Opened 2023-02-16 12:48 UTC by skabeo

Added an index.html file containing the content of the project, a styles folder containing the styles for the HTML file. Lastly, added an images folder containing every image used on the project.

2023-02-16 13:44 UTC, hiromataba requested changes
Hi @skabeo     :wave: :wave: 

![almost-there](https://user-images.githubusercontent.com/75126481/160092588-b3f37e8e-a1d9-4b14-84fc-7ec1fed7b3e5.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your PR has a proper title and description  :+1: 
- Your linters are passing :heavy_check_mark:  
- Profesional README file :rocket: 

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 13:44 UTC, hiromataba commented on styles/general.css
> +}
- [ ] For the background color please make sure that it matches the original design 

- Your design 👇 

![image](https://user-images.githubusercontent.com/75126481/219377909-ebe6e894-ea47-48a6-a228-19a19059dfb8.png)

- Origina design 👇 

![image](https://user-images.githubusercontent.com/75126481/219378099-b12fb80d-4e20-4b79-ba3b-034a88fb9bd8.png)

2023-02-16 13:44 UTC, hiromataba commented on index.html
> +        <p class="text-gradient">Welcome</p>
- [ ] [ OPTIONAL] I think it would be better to use you name here instead of `Welcome`

2023-02-16 13:44 UTC, hiromataba commented on index.html
> +        <img class="menu" src="img/menu.svg" alt="menu">
- [ ] Please use the same hamburger as the original design and you should use a the `nav` tag for the menu hamburger

- Original design 👇 
![image](https://user-images.githubusercontent.com/75126481/219378941-e3d3c106-4abe-4afa-a2ff-8da57b89c397.png)

- Your design 👇 

![image](https://user-images.githubusercontent.com/75126481/219379201-0c21eca2-b257-49f7-8617-fa3c030a389e.png)

2023-02-16 13:44 UTC, hiromataba commented on index.html
> +        <p class="text-gradient">Welcome</p>
- [ ] For the logo you should use the `a` tag so that it maybe clickable because a logo is always a link

2023-02-16 13:44 UTC, hiromataba commented on index.html
> +      </div>
- [ ] You should use the `ul` tag here as you did for the other icons to list the icons and `li` per icon

2023-02-16 13:44 UTC, hiromataba commented on styles/footer.css
> +  align-items: center;
- [ ] You did great using display flex 😉

2023-02-16 19:02 UTC, aamirkhan2478 requested changes
Hi @skabeo , 

![](https://media4.giphy.com/media/CoND5j6Bn1QZUgm1xX/giphy.gif)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Highlights
✔️ Good Effort
✔️ Your design is good.
✔️ Your PR has a proper title and description
✔️ Your linters are passing 
✔️ Profesional README file

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-16 19:02 UTC, aamirkhan2478 commented on index.html
> +          </ul>
- [ ] Well done you did a great job :+1:  but still some little bit changes are required please check below:

Your Design:
![screencapture-127-0-0-1-5500-2023-02-16-23_30_06](https://user-images.githubusercontent.com/45226848/219457442-9c03f6ea-1ac0-49d0-b8b4-0980180abc40.png)

Figma Design:
![219378099-b12fb80d-4e20-4b79-ba3b-034a88fb9bd8](https://user-images.githubusercontent.com/45226848/219457583-db7f3427-d417-4a43-98f8-283c5310d2c1.png)

- [ ] Please add this blur circle here then your design will be the same as the Figma design.

2023-02-16 19:02 UTC, aamirkhan2478 commented on styles/general.css
> +  font-family: 'Poppins', sans-serif;
- [ ] Kindly use the same font family as the Figma font family which is `Roboto`.

2023-02-16 19:02 UTC, aamirkhan2478 commented on index.html
> +            <img src="img/linkedin.svg" ></a></li>
- [ ] Kindly add all social media apps as mentioned in the Figma design:

![Screenshot from 2023-02-16 23-57-49](https://user-images.githubusercontent.com/45226848/219461718-d841d329-84a5-4687-8c6d-d5a060988756.png)

2023-02-17 08:51 UTC, wayungi approved these changes
Hi @skabeo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://user-images.githubusercontent.com/99656687/219597818-3585013f-9ca2-45e3-99bd-42946924951c.png)

## Highlights
- [ ] Profesional README ✔️ 
- [ ] All linter checks passing ✔️ 
- [ ] Good commit messages ✔️ 
- [ ] No merge conflicts ✔️ 
- [ ]  Correct GitHub flow ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-17 08:51 UTC, wayungi commented on index.html
> +        <a href="https://twitter.com/black_okyere"><p>Skabeo</p></a>
- [OOTIONAL] The logo should be a link that links back to the home page. You link leads to twitter 🐦

2023-02-17 09:25 UTC, merged